### ISSUE TITLE
Server启动后，如果没有注册的Client会一直抛出异常信息

### ISSUE THREAD

**Issue by hengboy** [minbox-projects/message-pipe#33]

**Comment by hengboy** [comment]
错误信息如下：
```
2020-08-24 14:07:16.674 ERROR 5863 --- [    admin-2-t-1] o.m.f.m.p.s.e.ConsoleExceptionHandler    : Encountered once while processing [org.minbox.framework.message.pipe.core.Message@189775cf] message.

org.minbox.framework.message.pipe.core.exception.MessagePipeException: Load balancing client list is empty.
	at org.minbox.framework.message.pipe.server.lb.support.RandomWeightedStrategy.lookup(RandomWeightedStrategy.java:32) ~[message-pipe-server-1.0.0-M1.jar:1.0.0-M1]
	at org.minbox.framework.message.pipe.server.distribution.MessageDistributionExecutor.sendMessage(MessageDistributionExecutor.java:110) [message-pipe-server-1.0.0-M1.jar:1.0.0-M1]
	at org.minbox.framework.message.pipe.server.distribution.MessageDistributionExecutor.takeAndSend(MessageDistributionExecutor.java:88) [message-pipe-server-1.0.0-M1.jar:1.0.0-M1]
	at org.minbox.framework.message.pipe.server.distribution.MessageDistributionExecutor.lambda$waitingForNewMessage$0(MessageDistributionExecutor.java:60) [message-pipe-server-1.0.0-M1.jar:1.0.0-M1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_231]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_231]
```
